# config/config.yaml - GLOBAL CONFIGURATION
environment: production

# Logging Configuration
logging:
  level: INFO
  file: logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Database Configuration
database:
  path: data/storage/support_levels.db
  backup_enabled: true
  backup_interval: 86400  # 24 hours in seconds

# API Configuration
api:
  binance:
    base_url: https://api.binance.com/api/v3
    timeout: 10
    rate_limit: 1200  # requests per minute
    retry_attempts: 3
    retry_delay: 1  # seconds

# Risk Management (Global)
risk:
  max_drawdown: 0.25
  daily_loss_limit: 0.02
  position_size: 0.02
  max_portfolio_risk: 0.02
  kill_switch_enabled: true

# Redis Configuration (untuk kill switch)
redis:
  host: localhost
  port: 6379
  db: 0
  password: null

# Monitoring & Alerts
monitoring:
  enabled: true
  dashboard_port: 8080
  update_interval: 60  # seconds
  alerts:
    telegram:
      enabled: false
      bot_token: ${TELEGRAM_BOT_TOKEN}
      chat_id: ${TELEGRAM_CHAT_ID}
    slack:
      enabled: false
      webhook_url: ${SLACK_WEBHOOK_URL}