# config/validation.yaml - VALIDATION & BACKTESTING CONFIG
# Migrated from: src/phase2_settings.py

# Basic Validation Configuration
validation:
  timeframe: 1d
  period_days: 1825            # 5 years (365 * 5)
  initial_balance: 10000
  base_commission: 0.001
  slippage_model: proportional
  
  thresholds:
    max_drawdown_limit: 0.25
    min_sharpe_ratio: 1.0
    min_win_rate: 0.50
    min_profit_factor: 1.3
  
  confidence:
    var_confidence_level: 0.95
    bootstrap_samples: 10000
    monte_carlo_simulations: 10000
    min_trade_threshold: 5
    correlation_threshold: 0.7

# Walk-Forward Analysis Configuration
walkforward:
  enabled: true
  
  windows:
    min_train_period: 730      # 2 years (365 * 2)
    max_train_period: 1095     # 3 years (365 * 3)
    test_period: 180           # 6 months
    step_size: 90              # 3 months step
    min_periods_required: 10
  
  optimization:
    metric: sharpe_ratio       # Options: sharpe_ratio, profit_factor, win_rate
    direction: maximize        # Options: maximize, minimize

# Monte Carlo Simulation
monte_carlo:
  enabled: true
  simulations: 10000
  confidence_intervals:
    - 0.90
    - 0.95
    - 0.99
  
  randomization:
    method: bootstrap          # Options: bootstrap, parametric, block_bootstrap
    preserve_order: false
    block_size: 20

# Stress Testing
stress_tests:
  enabled: true
  
  scenarios:
    - name: "2008_financial_crisis"
      description: "Simulate 2008-style market crash"
      return_shock: -0.50      # -50% returns
      volatility_multiplier: 3.0
      
    - name: "2020_covid_crash"
      description: "COVID-19 market crash scenario"
      return_shock: -0.35      # -35% returns
      volatility_multiplier: 2.5
      
    - name: "2017_crypto_crash"
      description: "Crypto bear market"
      return_shock: -0.80      # -80% returns
      volatility_multiplier: 4.0
      
    - name: "flash_crash"
      description: "Sudden liquidity crisis"
      return_shock: -0.25
      volatility_multiplier: 5.0
      duration_hours: 2
      
    - name: "high_correlation"
      description: "All assets move together"
      correlation_override: 0.95
      
    - name: "low_liquidity"
      description: "Slippage increases 10x"
      slippage_multiplier: 10.0
      fill_rate: 0.7

# Data Quality Checks
data_quality:
  min_completeness: 0.95       # 95% data completeness
  max_missing_days: 10
  max_zero_volume_pct: 0.05    # 5% max zero volume days
  detect_survivorship_bias: true
  validate_point_in_time: true

# Performance Metrics
performance_metrics:
  calculate:
    - sharpe_ratio
    - sortino_ratio
    - calmar_ratio
    - max_drawdown
    - profit_factor
    - win_rate
    - avg_win
    - avg_loss
    - expectancy
    - var_95
    - cvar_95
  
  benchmarks:
    sharpe_ratio:
      min_acceptable: 1.0
      good: 1.5
      excellent: 2.0
    max_drawdown:
      min_acceptable: -0.15
      good: -0.10
      excellent: -0.05
    profit_factor:
      min_acceptable: 1.3
      good: 2.0
      excellent: 3.0
    win_rate:
      min_acceptable: 0.45
      good: 0.55
      excellent: 0.65

# Validation Priority Coins (untuk testing awal)
priority_coins:
  high_priority:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
  
  medium_priority:
    - ADAUSDT
    - DOTUSDT
    - LINKUSDT
    - MATICUSDT
    - AVAXUSDT
  
  low_priority:
    - SOLUSDT
    - NEARUSDT
    - FTMUSDT